exports.Deck = [
  {
    id: 0,
    value: 1,
    img: "/cards/ace_of_clubs.png",
    suit: "clubs",
    abbreviation: "A♣",
  },
  {
    id: 1,
    value: 1,
    img: "/cards/ace_of_diamonds.png",
    suit: "diamonds",
    abbreviation: "A♦",
  },
  {
    id: 2,
    value: 1,
    img: "/cards/ace_of_hearts.png",
    suit: "hearts",
    abbreviation: "A♥",
  },
  {
    id: 3,
    value: 1,
    img: "/cards/ace_of_spades.png",
    suit: "spades",
    abbreviation: "A♠",
  },
  {
    id: 4,
    value: 2,
    img: "/cards/2_of_clubs.png",
    suit: "clubs",
    abbreviation: "2♣",
  },
  {
    id: 5,
    value: 2,
    img: "/cards/2_of_diamonds.png",
    suit: "diamonds",
    abbreviation: "2♦",
  },
  {
    id: 6,
    value: 2,
    img: "/cards/2_of_hearts.png",
    suit: "hearts",
    abbreviation: "2♥",
  },
  {
    id: 7,
    value: 2,
    img: "/cards/2_of_spades.png",
    suit: "spades",
    abbreviation: "2♠",
  },
  {
    id: 8,
    value: 3,
    img: "/cards/3_of_clubs.png",
    suit: "clubs",
    abbreviation: "3♣",
  },
  {
    id: 9,
    value: 3,
    img: "/cards/3_of_diamonds.png",
    suit: "diamonds",
    abbreviation: "3♦",
  },
  {
    id: 10,
    value: 3,
    img: "/cards/3_of_hearts.png",
    suit: "hearts",
    abbreviation: "3♥",
  },
  {
    id: 11,
    value: 3,
    img: "/cards/3_of_spades.png",
    suit: "spades",
    abbreviation: "3♠",
  },
  {
    id: 12,
    value: 4,
    img: "/cards/4_of_clubs.png",
    suit: "clubs",
    abbreviation: "4♣",
  },
  {
    id: 13,
    value: 4,
    img: "/cards/4_of_diamonds.png",
    suit: "diamonds",
    abbreviation: "4♦",
  },
  {
    id: 14,
    value: 4,
    img: "/cards/4_of_hearts.png",
    suit: "hearts",
    abbreviation: "4♥",
  },
  {
    id: 15,
    value: 4,
    img: "/cards/4_of_spades.png",
    suit: "spades",
    abbreviation: "4♠",
  },
  {
    id: 16,
    value: 5,
    img: "/cards/5_of_clubs.png",
    suit: "clubs",
    abbreviation: "5♣",
  },
  {
    id: 17,
    value: 5,
    img: "/cards/5_of_diamonds.png",
    suit: "diamonds",
    abbreviation: "5♦",
  },
  {
    id: 18,
    value: 5,
    img: "/cards/5_of_hearts.png",
    suit: "hearts",
    abbreviation: "5♥",
  },
  {
    id: 19,
    value: 5,
    img: "/cards/5_of_spades.png",
    suit: "spades",
    abbreviation: "5♠",
  },
  {
    id: 20,
    value: 6,
    img: "/cards/6_of_clubs.png",
    suit: "clubs",
    abbreviation: "6♣",
  },
  {
    id: 21,
    value: 6,
    img: "/cards/6_of_diamonds.png",
    suit: "diamonds",
    abbreviation: "6♦",
  },
  {
    id: 22,
    value: 6,
    img: "/cards/6_of_hearts.png",
    suit: "hearts",
    abbreviation: "6♥",
  },
  {
    id: 23,
    value: 6,
    img: "/cards/6_of_spades.png",
    suit: "spades",
    abbreviation: "6♠",
  },
  {
    id: 24,
    value: 7,
    img: "/cards/7_of_clubs.png",
    suit: "clubs",
    abbreviation: "7♣",
  },
  {
    id: 25,
    value: 7,
    img: "/cards/7_of_diamonds.png",
    suit: "diamonds",
    abbreviation: "7♦",
  },
  {
    id: 26,
    value: 7,
    img: "/cards/7_of_hearts.png",
    suit: "hearts",
    abbreviation: "7♥",
  },
  {
    id: 27,
    value: 7,
    img: "/cards/7_of_spades.png",
    suit: "spades",
    abbreviation: "7♠",
  },
  {
    id: 28,
    value: 8,
    img: "/cards/8_of_clubs.png",
    suit: "clubs",
    abbreviation: "8♣",
  },
  {
    id: 29,
    value: 8,
    img: "/cards/8_of_diamonds.png",
    suit: "diamonds",
    abbreviation: "8♦",
  },
  {
    id: 30,
    value: 8,
    img: "/cards/8_of_hearts.png",
    suit: "hearts",
    abbreviation: "8♥",
  },
  {
    id: 31,
    value: 8,
    img: "/cards/8_of_spades.png",
    suit: "spades",
    abbreviation: "8♠",
  },
  {
    id: 32,
    value: 9,
    img: "/cards/9_of_clubs.png",
    suit: "clubs",
    abbreviation: "9♣",
  },
  {
    id: 33,
    value: 9,
    img: "/cards/9_of_diamonds.png",
    suit: "diamonds",
    abbreviation: "9♦",
  },
  {
    id: 34,
    value: 9,
    img: "/cards/9_of_hearts.png",
    suit: "hearts",
    abbreviation: "9♥",
  },
  {
    id: 35,
    value: 9,
    img: "/cards/9_of_spades.png",
    suit: "spades",
    abbreviation: "9♠",
  },
  {
    id: 36,
    value: -10,
    img: "/cards/10_of_clubs.png",
    suit: "clubs",
    abbreviation: "10♣",
  },
  {
    id: 37,
    value: -10,
    img: "/cards/10_of_diamonds.png",
    suit: "diamonds",
    abbreviation: "10♦",
  },
  {
    id: 38,
    value: -10,
    img: "/cards/10_of_hearts.png",
    suit: "hearts",
    abbreviation: "10♥",
  },
  {
    id: 39,
    value: -10,
    img: "/cards/10_of_spades.png",
    suit: "spades",
    abbreviation: "10♠",
  },
  {
    id: 40,
    value: 10,
    img: "/cards/jack_of_clubs2.png",
    suit: "clubs",
    abbreviation: "J♣",
  },
  {
    id: 41,
    value: 10,
    img: "/cards/jack_of_diamonds2.png",
    suit: "diamonds",
    abbreviation: "J♦",
  },
  {
    id: 42,
    value: 10,
    img: "/cards/jack_of_hearts2.png",
    suit: "hearts",
    abbreviation: "J♥",
  },
  {
    id: 43,
    value: 10,
    img: "/cards/jack_of_spades2.png",
    suit: "spades",
    abbreviation: "J♠",
  },
  {
    id: 44,
    value: 10,
    img: "/cards/queen_of_clubs2.png",
    suit: "clubs",
    abbreviation: "Q♣",
  },
  {
    id: 45,
    value: 10,
    img: "/cards/queen_of_diamonds2.png",
    suit: "diamonds",
    abbreviation: "Q♦",
  },
  {
    id: 46,
    value: 10,
    img: "/cards/queen_of_hearts2.png",
    suit: "hearts",
    abbreviation: "Q♥",
  },
  {
    id: 47,
    value: 10,
    img: "/cards/queen_of_spades2.png",
    suit: "spades",
    abbreviation: "Q♠",
  },
  {
    id: 48,
    value: 10,
    img: "/cards/king_of_clubs2.png",
    suit: "clubs",
    abbreviation: "K♣",
  },
  {
    id: 49,
    value: 10,
    img: "/cards/king_of_diamonds2.png",
    suit: "diamonds",
    abbreviation: "K♦",
  },
  {
    id: 50,
    value: 10,
    img: "/cards/king_of_hearts2.png",
    suit: "hearts",
    abbreviation: "K♥",
  },
  {
    id: 51,
    value: 10,
    img: "/cards/king_of_spades2.png",
    suit: "spades",
    abbreviation: "K♠",
  },
];